# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbImage = QtWidgets.QLabel(self.centralwidget)
        self.lbImage.setEnabled(True)
        self.lbImage.setGeometry(QtCore.QRect(26, 30, 621, 491))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(36)
        self.lbImage.setFont(font)
        self.lbImage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbImage.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lbImage.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lbImage.setObjectName("lbImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(True)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setCheckable(True)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionOpen_3 = QtWidgets.QAction(MainWindow)
        self.actionOpen_3.setObjectName("actionOpen_3")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Exit_2 = QtWidgets.QAction(MainWindow)
        self.action_Exit_2.setCheckable(False)
        self.action_Exit_2.setIconVisibleInMenu(False)
        self.action_Exit_2.setObjectName("action_Exit_2")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Exit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Open.triggered.connect(self.open_file)
        self.action_Exit_2.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbImage.setText(_translate("MainWindow", "        Image Here"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_3.setText(_translate("MainWindow", "&Open"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Exit_2.setText(_translate("MainWindow", "&Exit"))

    def open_file(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        path = filename[0]
        pixmap = QPixmap(path)
        self.image = cv2.imread(path)
        self.lbImage.setPixmap(pixmap)
        self.lbImage.setScaledContents(True)
        self.lbImage.show()
        # self.image = cv2.imshow("lmao", self.image)
        cv2.waitKey(0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
